### ISSUE TITLE
Generate report by Division and Department

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/kool-aide#34]
**Describe the enhancement**
Can we provide/set Division and Department for report generation? For example if this gets implemented in QA, we would like their report to  contain data for QA only. Same for Dev.

**Describe the proposed solution**
Parameterized to generate by division/department or generate all

**Comment by trashvin** [comment]
@charissasylim , this is currently supported by the parameters e.g. kool-aide generate-report -r [report name] --params {''\divisions\":[1], \"departments\":[2]}.
