### ISSUE TITLE
[Comm Cell Schedule] Has 2 March entry

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/kool-aide#36]
**Describe the bug**
Report has 2 entries for month of March

**Expected behavior**
1 March Month per FY

**Screenshots**
![image](https://user-images.githubusercontent.com/52391236/74116333-167fdf00-4bee-11ea-9451-fd4236f26bf5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Report   generated : 2020-02-09 20:01:06.018065 by kool-aide v0.8.0

**Comment by trashvin** [comment]
@charissasylim , this was a data error. The first entry have wrong FY_END. This is fixed.
