### ISSUE TITLE
[Billability] Start of the month's reporting does not match with AIDE Productivity KPI Summary reporting

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/kool-aide#45]
**Describe the bug**
Sample -
In AIDE, Productivity - KPI Summary reporting for Monthly Hours starts week of 8/29/2020
In Kool-Aide, Billability report starts week ending of 9/11. Noticed that August report did not cover week ending 9/4. This is also not in September report.

There is a 1 week difference in reporting thus Billable Hours and Non Billable Percentage and Hours are not equal for both.

**To Reproduce**

**Expected behavior**
Follow AIDE behavior in capturing the monthly data.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by trashvin** [comment]
This fixed. Reports for September has been regenerated.
